### ISSUE TITLE
tensors are on different GPUs

### ISSUE THREAD

**Issue by liye228** [jacobkimmel/pytorch_convgru#1]
@jacobkimmel 
hello!
Thanks for your code, it can run on a gpu.
However, when I run it on two gpus, it failed!
error message:
tensors are on different GPUs

Can you help me?

**Comment by jacobkimmel** [comment]
If you tried to assign different parts of the module to different GPUs but didn't properly pass tensors between them (i.e. `tensor_on_cuda1 = tesnor_on_cuda0.cuda(1)`), you probably ran into this error. 

I'm not sure what you're doing, so it's hard to be more helpful, but make sure that you effectively line up all your tensors on the same GPU as the appropriate parameters for an op to execute! If you put the ConvGRUs on GPU 1, and the tensors on 0, you'll need to move them over to actually operate.

**Comment by naveenventuri** [comment]
Hi @liye228 ,
Did you resolve the error with multiple GPU'S?

**Comment by Harrypotterrrr** [comment]
@naveenventuri  Hi have you solved this problem? multi-gpu problem still exits
