### ISSUE TITLE
Can't help say something about this repo

### ISSUE THREAD

**Issue by JasonLeeFdu** [jacobkimmel/pytorch_convgru#11]
1. terrible variable naming
2. hidden states are not passed in the GRU chain
3. nn.Module list question that is already mentioned in other "issues"

1.变量名取得比较不准确混乱
2. 隐状态其实并没有在GRU链条中传递，使用方式也有问题
3. 其他issue也提到 nn.ModuleList问题

**Comment by jacobkimmel** [comment]
1. The names are common descriptors
