### ISSUE TITLE
Multiple GPUs running issue

### ISSUE THREAD

**Issue by naveenventuri** [jacobkimmel/pytorch_convgru#5]
Hi,
When i tried to run this code on multiple gpus i got an error saying that tenors are on different GPUs

**Comment by jacobkimmel** [comment]
Hey @naveenventuri,

You probably forgot to pass a tensor between the GPUs, or didn't move all the GRUCells in the GRU onto the same GPU. 
Without seeing your code, it's hard to be more helpful.

Thanks!
Jacob
